#!/bin/sh

cp -a debian/tests/packages "$AUTOPKGTEST_TMP"
dist_packages=/usr/local/lib/python3.12/dist-packages

setUp() {
	mount -t tmpfs tmpfs $dist_packages
}

tearDown() {
	umount $dist_packages
}

testFibPy() {
	cd "$AUTOPKGTEST_TMP/packages/fibpy"
	python3.12 setup.py install
	assertTrue 'Install fibpy in /usr/local' $?
	assertTrue 'fibpy was installed to /usr/local' "[ -e $dist_packages/fibpy-*.egg ]"
	cd "$AUTOPKGTEST_TMP"
	stdout=$(python3.12 -m fibpy 5)
	assertTrue 'Execute fibpy from /usr/local' $?
	assertEquals 'Correct result' 8 "$stdout"
}

testFibC() {
	cd "$AUTOPKGTEST_TMP/packages/fibc"
	python3.12 setup.py install
	assertTrue 'Install fibc in /usr/local' $?
	assertTrue 'fibc was installed to /usr/local' "[ -e $dist_packages/fibc-*.egg ]"
	cd "$AUTOPKGTEST_TMP"
	stdout=$(python3.12 -c 'from fibc import fib; print(fib(5))')
	assertTrue 'Execute fibc from /usr/local' $?
	assertEquals 'Correct result' 8 "$stdout"
}

testFibPyDevelop() {
	cd "$AUTOPKGTEST_TMP/packages/fibpy"
	python3.12 setup.py develop
	assertTrue 'Install editable fibpy in /usr/local' $?
	assertTrue 'fibpy was linked to /usr/local' "[ -e $dist_packages/fibpy.egg-link ]"
	cd "$AUTOPKGTEST_TMP"
	stdout=$(python3.12 -m fibpy 5)
	assertTrue 'Execute editable fibpy from /usr/local' $?
	assertEquals 'Correct result' 8 "$stdout"
}

testFibPyPip() {
	cd "$AUTOPKGTEST_TMP"
	python3.12 -m pip install --break-system-packages --no-build-isolation \
		-v "$AUTOPKGTEST_TMP/packages/fibpy"
	assertTrue 'Install fibpy via pip in /usr/local' $?
	assertTrue 'fibpy was installed to /usr/local' "[ -e $dist_packages/fibpy.py ]"
	stdout=$(python3.12 -m fibpy 5)
	assertTrue 'Execute fibpy from /usr/local' $?
	assertEquals 'Correct result' 8 "$stdout"
}

testFibPyPipEditable() {
	cd "$AUTOPKGTEST_TMP"
	python3.12 -m pip install --no-build-isolation --break-system-packages\
		-v -e "$AUTOPKGTEST_TMP/packages/fibpy"
	assertTrue 'Install editable fibpy via pip in /usr/local' $?
	assertTrue 'fibpy was linked to /usr/local' "[ -e $dist_packages/__editable__.fibpy-42.0.0.pth ]"
	stdout=$(python3.12 -m fibpy 5)
	assertTrue 'Execute fibpy from /usr/local' $?
	assertEquals 'Correct result' 8 "$stdout"
}

. shunit2
